# For all the available configuration options, please view the following file:
#
# https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml
#

# MD013/line-length : Line length : https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md013.md
MD013:
  # Number of characters
  line_length: 120
  # Include tables
  tables: false

# MD033/no-inline-html : Inline HTML : https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md033.md
"MD033": false

