[tool.isort]
profile = "black"
src_paths = ["apps", "coded_tools", "tests"]
line_length = 119
known_first_party = ["apps"]

[tool.flake8]
extend-ignore = ["W503", "E203"]
max-line-length = 119

[tool.black]
line-length = 119
required-version = "25.1.0"

[tool.pylint]
max-line-length = 119
# Based on Google Python Style Guide
disable = [
    "C0301",  # Line too long (handled by black)
    "C0114",  # Missing module docstring (missing-module-docstring)
    # This repo contains examples that should remain independent, so we expect some level of copy/paste
    "R0801",  # Similar lines in 2 files
    "W0511",  # TODO/FIXME comments
    ]
good-names = ["i", "j", "k", "ex", "_", "id", "f", "db", "e"]
ignore-patterns = [".*checkpoint\\.py"]
ignore-paths = ["^venv/.*$", "^.*/\\.venv/.*$"]
# Google style requires docstrings
enable = [
    "useless-suppression",
]
# Google style naming conventions
const-naming-style = "UPPER_CASE"
function-naming-style = "snake_case"
class-naming-style = "PascalCase"
method-naming-style = "snake_case"
attr-naming-style = "snake_case"
argument-naming-style = "snake_case"
variable-naming-style = "snake_case"
inlinevar-naming-style = "snake_case"
# Additional settings
fail-under = 10.0
output-format = "colorized"
init-import = false

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
addopts = "--verbose --cov=. --cov-report=term-missing --no-cov-on-fail"

[tool.coverage.run]
omit = ["tests/*", "*/venv/*"]
